#!/bin/bash

LOCATION=$(curl -s ipinfo.io)

CITY=$(echo $LOCATION | jq .city | sed 's/^.//;s/.$//')
COUNTRY=$(echo $LOCATION | jq .country | sed 's/^.//;s/.$//')
INITIAL_COUNTRY="PL"

if [[ "${COUNTRY}" != "${INITIAL_COUNTRY}"  ]]; then
	echo "<span color='#f39c12'>${CITY}</span>"
else
	echo "${CITY}"
fi
